#!/usr/bin/env python3
"""
Example of how to use curvedelta results with slitdec.

This script demonstrates loading the slitcurve and residual slitdeltas
from the NPZ files generated by make_curvedelta.py and passing them to slitdec.
"""

import numpy as np
from astropy.io import fits
import slitchar

# Load FITS file
fits_file = "data/Hsim.fits"
with fits.open(fits_file) as hdul:
    im = hdul[0].data

nrows, ncols = im.shape

# Load curvedelta results
curvedelta_file = "data/curvedelta_Hsim.npz"
data = np.load(curvedelta_file)

slitcurve = np.ascontiguousarray(data["slitcurve"], dtype=np.float64)  # Shape: (ncols, 3)
slitdeltas = np.ascontiguousarray(data["slitdeltas"], dtype=np.float64)  # Shape: (nrows,)
ycen_value = float(data["ycen_value"])  # Scalar, e.g., 0.5

print(f"Loaded curvedelta data from: {curvedelta_file}")
print(f"  slitcurve shape: {slitcurve.shape}")
print(f"  slitdeltas shape: {slitdeltas.shape}")
print(f"  ycen_value: {ycen_value}")
print()

# Set up other parameters for slitdec
im = np.ascontiguousarray(im, dtype=np.float64)
pix_unc = np.ascontiguousarray(np.sqrt(np.abs(im) + 1.0), dtype=np.float64)
mask = np.ascontiguousarray(np.ones_like(im, dtype=np.uint8))
ycen = np.ascontiguousarray(np.full(ncols, ycen_value), dtype=np.float64)  # Constant ycen for all columns
osample = 6
lambda_sP = 0.0
lambda_sL = 0.1

print("Calling slitdec with curvature correction...")
result = slitchar.slitdec(
    im=im,
    pix_unc=pix_unc,
    mask=mask,
    ycen=ycen,
    slitcurve=slitcurve,
    slitdeltas=slitdeltas,
    osample=osample,
    lambda_sP=lambda_sP,
    lambda_sL=lambda_sL,
)

print("✓ slitdec completed successfully!")
print(f"  Spectrum shape: {result['spectrum'].shape}")
print(f"  Slit function shape: {result['slitfunction'].shape}")
print(f"  Model shape: {result['model'].shape}")
print()

# Compare with zero curvature
print("For comparison, calling slitdec with zero curvature...")
slitcurve_zero = np.zeros_like(slitcurve)
slitdeltas_zero = np.zeros_like(slitdeltas)

result_zero = slitchar.slitdec(
    im=im,
    pix_unc=pix_unc,
    mask=mask,
    ycen=ycen,
    slitcurve=slitcurve_zero,
    slitdeltas=slitdeltas_zero,
    osample=osample,
    lambda_sP=lambda_sP,
    lambda_sL=lambda_sL,
)

print("✓ slitdec completed (zero curvature)!")
print()

# Calculate reconstruction quality
residual_with_curve = im - result["model"]
residual_zero_curve = im - result_zero["model"]

rms_with_curve = np.sqrt(np.mean(residual_with_curve**2))
rms_zero_curve = np.sqrt(np.mean(residual_zero_curve**2))

print("Reconstruction quality (RMS residual):")
print(f"  With curvature correction: {rms_with_curve:.4f}")
print(f"  Without curvature: {rms_zero_curve:.4f}")
print(f"  Improvement: {(1 - rms_with_curve/rms_zero_curve)*100:.2f}%")
